AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: CupidonChick Backend

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        MONGODB_URI: !Ref MongoDBUri
        SENTRY_DSN: !Ref SentryDsn

Parameters:
  MongoDBUri:
    Type: String
  SentryDsn:
    Type: String

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-backend"
      Handler: src/serverless.handler
      Runtime: nodejs20.x
      CodeUri: ./
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
